# Simple Terraform configuration using local resources
terraform {
  required_version = ">= 1.0"
}

# Local file for application configuration
resource "local_file" "app_config" {
  filename = "application-terraform.properties"
  content  = <<-EOT
    # Application Configuration - Generated by Terraform
    app.name=Test_PFE_Spring_Boot
    app.version=1.0.0
    terraform.deployed=true
    deployment.timestamp=${timestamp()}
    database.name=foyer
    spring.profiles.active=terraform
  EOT
}

# Configuration file for Docker
resource "local_file" "docker_env" {
  filename = ".env.terraform"
  content  = <<-EOT
    # Docker Environment - Generated by Terraform
    SPRING_PROFILES_ACTIVE=terraform
    TERRAFORM_DEPLOYED=true
    APP_VERSION=1.0.0
    DEPLOYMENT_TIMESTAMP=${timestamp()}
  EOT
}

# Documentation file
resource "local_file" "terraform_readme" {
  filename = "INFRASTRUCTURE.md"
  content  = <<-EOT
    # Infrastructure as Code (IaC)

    This infrastructure is managed by Terraform.

    ## Resources Managed:
    - Application configuration files
    - Environment variables for Docker
    - Documentation

    ## Files Created:
    1. `application-terraform.properties` - Spring Boot configuration
    2. `/.env.terraform` - Docker environment variables  
    3. `INFRASTRUCTURE.md` - This file

    ## Terraform Commands:
    ```bash
    # Initialize Terraform
    terraform init

    # Plan changes
    terraform plan

    # Apply configuration
    terraform apply

    # Destroy resources
    terraform destroy
    ```

    ## Deployment Details:
    - Project: Test_PFE Spring Boot Application
    - Managed by: Terraform
    - Deployment Time: ${timestamp()}
  EOT
}

# Output the created resources
output "created_files" {
  description = "List of files created by Terraform"
  value = {
    app_config    = local_file.app_config.filename
    docker_env    = local_file.docker_env.filename
    documentation = local_file.terraform_readme.filename
  }
}

output "deployment_summary" {
  description = "Summary of the Terraform deployment"
  value       = <<-EOT
    Terraform Local Deployment Completed!

    Created the following files:
    ✅ ${local_file.app_config.filename} - Application configuration
    ✅ ${local_file.docker_env.filename} - Docker environment variables  
    ✅ ${local_file.terraform_readme.filename} - Infrastructure documentation

    You can now:
    1. Use these configurations in your Spring Boot app
    2. Reference the environment variables in Docker
    3. Review the infrastructure documentation

    Run 'terraform destroy' to remove these files.
  EOT
}